-- AgriSmart AI - Supabase PostgreSQL Schema
-- Run this in your Supabase Project -> SQL Editor to initialize all cloud tables

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email_or_phone TEXT UNIQUE NOT NULL,
    location TEXT DEFAULT 'Ahmedabad, Gujarat',
    primary_crop TEXT DEFAULT 'Tomato',
    language TEXT DEFAULT 'en',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Disease Diagnoses Table
CREATE TABLE IF NOT EXISTS public.diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    crop TEXT NOT NULL,
    disease TEXT NOT NULL,
    class_label TEXT NOT NULL,
    confidence REAL NOT NULL,
    is_disease BOOLEAN NOT NULL,
    symptoms TEXT,
    precautions TEXT,
    treatment TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. IoT Sensor Telemetry & Farm Logs Table
CREATE TABLE IF NOT EXISTS public.farm_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    soil_moisture REAL,
    temperature REAL,
    humidity REAL,
    soil_ph REAL,
    decision TEXT,
    water_saved_liters REAL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diagnoses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.farm_logs ENABLE ROW LEVEL SECURITY;

-- Allow public read/write policies for the AgriSmart API service key
CREATE POLICY "Allow public read users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Allow public insert users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read diagnoses" ON public.diagnoses FOR SELECT USING (true);
CREATE POLICY "Allow public insert diagnoses" ON public.diagnoses FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read farm_logs" ON public.farm_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert farm_logs" ON public.farm_logs FOR INSERT WITH CHECK (true);
